import unlockit from "./assets/unlockit.png";
import algoholics from "./assets/algoholics.png";
import paper from "./assets/paper-presentation.jpg";
import blindcoding from "./assets/blindcoding.jpg";
import web from "./assets/web.jpg";
import debug from "./assets/debug.png";

const tech = [
  {
    id: "1",
    title: "Unlock-IT",
    desc: `Welcome to the IT-quiz that focuses on testing knowledge and basic understanding of computer science subjects, such as C/C++ Language, Object oriented programming, Data structures, Operating systems and many more...`,
    image: unlockit,
    rules: [
      "It is a team event with minimum of 2 and maximum of 4 members.",
      "Teams can be formed irrespective of their branch and year.",
      "There will be 2 rounds - ",
      "1st round will be written quiz having questions related to C/C++ and OOPS. Out of which top 6 teams will be selected for next round.",
      "2nd round will be having questions on basics of OOPS, OS, Networks, DBMS etc.",
    ],
    coordinators: [
      { name: "Chinmayi", phno: "7892312519" },
      { name: "Shree Gowri", phno: "9353709717" },
      { name: "Latha", phno: "8088564778" },
      { name: "Arpitha", phno: "9731962554" },
      { name: "Darshan MN", phno: "8088566924" },
      { name: "Harish", phno: "9900488690" },
    ],
    timing: "11:00am - 1:00pm",
    date: "30/03/2023",
    link: "https://forms.gle/fKdjaDdQtoFS228g7",
  },
  {
    id: "2",
    title: "AlgoHolics",
    desc: "Welcome to coding competition which provides you with the oppurtunity to meet and brainstorm with other like minded peoples. Algorithm as a recipe that describes the exact steps needed for the computer to solve a problem. Enjoy making coding recipes..",
    image: algoholics,
    rules: [
      "It is a coding event with maximum of 3 members.",
      "Indvidual participation is also allowed",
      "Teams can be formed irrespective of their branch and year.",
      "There will be 2 rounds - ",
      "1st round will be having 1 Algorithm which you need to code and execute",
      "Top 10 teams will be selected for final round",
      "In 2nd round 2 Algorithms will be given for coding",
      "Coding can be done in any of the given languages (C,C++,Java,Python)",
    ],
    coordinators: [
      { name: "Keertana S", phno: "9148572175" },
      { name: "Madhuri", phno: "9148188973" },
      { name: "Manuja", phno: "6363943776" },
      { name: "Pranathi", phno: "8431476132" },
      { name: "Swathi A", phno: "9019635272" },
      { name: "Abhilash", phno: "9008156750" },
      { name: "Devraj", phno: "8105506467" },
    ],
    timing: "9:30am - 12:30pm",
    date: "31/03/2023",
    link: "https://forms.gle/yMpEYN6BeaXAEpcG7",
  },
  {
    id: "3",
    title: "Present Smartly",
    desc: "Paper presentation is the oral summary of an accomplished research study of an empirical or theoretical nature. The presenters are requested to present their papers with only occasional reference to their notes rather than by reading out previously prepared texts.",
    image: paper,
    rules: [
      "Maximum 2 participants per paper are allowed",
      "Teams can be formed irrespective of their branch and year.",
      "Time limit : 8 + 2 mins",
      "Paper should be in IEEE format only.",
      "Topics cam be choosen from any technial domain.",
      "Paper should be sent via mail to suhasmallya15@gmail.com on or before 30th March.",
      "Hard copy should be submitted during paper presentation.",
      "Registered student must bring soft copy of Paper presentation PPT in USB drive.",
    ],
    coordinators: [
      { name: "Sumathi", phno: "8088232716" },
      { name: "Pooja N", phno: "9611343393" },
      { name: "Nayana", phno: "8088562248" },
      { name: "Pooja K", phno: "6364831626" },
      { name: "Sai Ganesh", phno: "9148061549" },
    ],
    timing: "11:00am - 12:00pm",
    date: "31/03/2023",
    link: "https://forms.gle/gdj55hjTtBKedjL3A",
  },
  {
    id: "4",
    title: "Blind Coding",
    desc: "Blind Coding is where a programmer works on code without running it until completion. Normally this is a terrible idea but it makes for a very fun challenge! This activity mainly tests your concentration, accuracy, programming skills.",
    image: blindcoding,
    rules: [
      "This is an Individual Event.",
      "The compiler provided will be codeblocks",
      "This event consists of two rounds.",
      "Participants have to write code with monitors off.",
      "Coding can be done in any of the given languages (C,C++)",
      "Participants whose code gets executed will be given higher preference.",
      "The second preference will be given to code with least number of errors.",
      "In case of tie in number of errors, TIME of SUBMISSION will be considered.",
    ],
    coordinators: [
      { name: "Shamshadh", phno: "7795581611" },
      { name: "Chandana T", phno: "8762110419" },
      { name: "Bhoomika S", phno: "9019876491" },
      { name: "Rani", phno: "9008241561" },
      { name: "Nitish", phno: "7619202355" },
      { name: "Ramesh", phno: "7996786287" },
    ],
    timing: "2:00pm - 4:00pm",
    date: "30/03/2023",
    link: "https://forms.gle/VrCVYxTNisdNCUvZA",
  },
  {
    id: "5",
    title: "Spin-A-Web",
    desc: "The competition is about designing the layout of a website using the basic HTML and CSS codes. The objective of this competition is to motivate students to spend time in meaningful activity and to be a creator of the digital world instead of a consumer.",
    image: web,
    rules: [
      "It is a coding event with maximum of 3 members.",
      "Indvidual participation is also allowed",
      "Teams can be formed irrespective of their branch and year.",
      "Team will be given a basic web design image which has to be coded using HTML and CSS only",
      "No other framework/library is allowed",
      "Each team will be given a system. No need of laptop.",
    ],
    coordinators: [
      { name: "Rakshitha", phno: "6360245401" },
      { name: "Bhuvana", phno: "9902165388" },
      { name: "Bindhu", phno: "9739444389" },
      { name: "Ankita", phno: "7899405036" },
      { name: "Nandini", phno: "6360234851" },
      { name: "Keerthana M", phno: "7619644843" },
      { name: "Parichith", phno: "9886111229" },
      { name: "Sagar", phno: "7022274129" },
    ],
    timing: "11:00am - 1:00pm",
    date: "31/03/2023",
    link: "https://forms.gle/UAXPTWvDdLhXrC5q6",
  },
  {
    id: "6",
    title: "Debug++",
    desc: "Debugging is an art of finding the root of a problem in a code base and fixing it. There's no magic solution for bugs. Usually it takes a combination of googling, logging our code, and checking our logic against what is really happening.",
    image: debug,
    rules: [
      "This is an Individual Event.",
      "The error code will be given in text file (notepad)",
      "The code will be in C language only.",
      "One who debug more errors will be given higher preference.",
      "The code will be based on array, searching, sorting, basic math.",
    ],
    coordinators: [
      { name: "Anusha", phno: "9591149642" },
      { name: "Chaitra", phno: "8971863287" },
      { name: "Najma", phno: "9148022586" },
      { name: "Aishwarya C", phno: "7259691533" },
      { name: "Ramyashree", phno: "9148191578" },
      { name: "Manoj", phno: "6363893636" },
      { name: "Mahantesh", phno: "9986654564" },
    ],
    timing: "11:30am - 1:00pm",
    date: "30/03/2023",
    link: "https://forms.gle/gZoJ7YU71GSKDMkp9",
  },
];

export default tech;
